### ISSUE TITLE
Thanks that the install guide is wrong

### ISSUE THREAD

**Issue by LeviD77** [spatie/laravel-analytics#139]
So my last hour was trying to figure out why you're install guide is all wrong and why I can not by any chance publish the vendor. I found on a completely different forum, that instead of:

`Spatie\Analytics\AnalyticsServiceProvider::class,
'Analytics' => Spatie\Analytics\AnalyticsFacade::class,
php artisan vendor:publish --provider="Spatie\Analytics\AnalyticsServiceProvider"`

You need to change all of them to:

`Spatie\LaravelAnalytics\LaravelAnalyticsServiceProvider::class
'Analytics' => Spatie\LaravelAnalytics\LaravelAnalyticsFacade::class
php artisan vendor:publish --provider="Spatie\LaravelAnalytics\LaravelAnalyticsServiceProvider"`

For god's sake. Please make a right installation guide or do not do public packages.

Thanks,
A concerned dev

**Comment by freekmurze** [comment]
Hi, 

the readme displayed on GitHub is for the latest version of the package: `v2`. That version requires PHP 7. 

If you do not have PHP 7 installed composer will pull in a compatible version, in this case `v1`. If you use the tag switcher, you can view the readme for that version. 

![screen shot 2016-12-07 at 15 34 33](https://cloud.githubusercontent.com/assets/483853/20971690/b4ae83aa-bc92-11e6-8712-e60524481c86.png)

Though I'm not certain you meant it that way, this sentence sounds a bit rude:

> For god's sake. Please make a right installation guide or do not do public packages.

Do keep in mind that we and all maintainers put free time in our packages.  Getting to use open source is a privilege, not a right. Try to keep that in mind when posting issues.

Thanks,
A concerned contributor

**Comment by LeviD77** [comment]
I see. This very much solves the problem. Though as I have found tons of forums about this problems, I beleiev it would be essential to keep this kind of information in the docs.

**Comment by PendoNL** [comment]
What an attitude towards a company full of people dedicating tons of time into open-source, coming from some random user who hasn't contributed to anything during his over 3 year stay at Github. Unbelievable.

Thumbs up for Spatie!

**Comment by amosmos** [comment]
@LeviD77 Even if *theoretically* the problem was indeed in the docs (and not in the fact you were installing v1 and looking at the v2 instructions), your comment is wrong and infuriating. If someone decides to publish a package to the public, it still doesn't mean he owes anything to anyone. You don't have to use the package if you don't want.

But since indeed the problem you encountered was caused by your wrong doing, I would also suggest that for the future you remember always to assume *you're* doing something wrong as you're asking for support from the author of an OS package.
