### ISSUE TITLE
Multiple dimensions

### ISSUE THREAD

**Issue by MattyFromLE** [spatie/laravel-analytics#186]
Hey Freek! I spoke to you briefly on Twitter. I'm currently using this query: 

`$pageViews = Analytics::performQuery(Period::days(7), 'ga:uniquePageviews', ['dimensions'=>'ga:pageTitle','sort'=>'-ga:uniquePageviews']);
        $result = collect($pageViews['rows'] ?? [])->map(function (array $dateRow) {
            
            return [

               'page' =>  $dateRow[0],
               'uniquePageviews' => (int) $dateRow[1],

            ];

        });`

...and it's working fine! However, I want to be able to use more than one dimension, so - i'd like to be able to do something like: 
`$pageViews = Analytics::performQuery(Period::days(7), 'ga:uniquePageviews', ['dimensions'=>['ga:pageTitle', 'ga:anotherDimension','ga:anotherDimension'],'sort'=>'-ga:uniquePageviews']);`

...or something? 

Apologies if this is a repeat question. 

Matty

**Comment by freekmurze** [comment]
Hi Matty,

unfortunately I don't know how to do this by heart. Toy a bit around with the package to find out how to achieve this. Would you mind posting the answer here for users who might have the same question in the future?

**Comment by MackEdweise** [comment]
I toyed around a bit and got it working with multiple dimensions. The Google Analytics API package will accept comma delimited dimensions like so 'ga:pagePath,ga:country,ga:date'. :)

**Comment by EAlexis92** [comment]
That is not the correct way, as you can see when you print the URI for the query its suppose to match or be as close as possible to this API Query URI = https://www.googleapis.com/analytics/v3/data/ga?ids=ga%3A194520602&start-date=28daysAgo&end-date=yesterday&metrics=ga%3Apageviews%2Cga%3AsessionDuration%2Cga%3Aexits&dimensions=ga%3Asource&sort=-ga%3Apageviews&filters=ga%3Amedium%3D%3Dreferral. Meaning that the 2nd param after the date is all the metrics you want. So for example:

Analytics::performQuery(

            Period::days(static::$time[2]),
            'ga:exits, ga:pageviews, ga:sessionDuration',
            [
                'dimensions' => 'ga:source',
                'sort' => '-ga:exits',
                'filters' => 'ga:medium==referral'
            ]
        );

This gives you the URI I gave above, the documentation is very unclear on this. It does tell you that the first param is the metric but WTF is with this example that I will show??? 

//retrieve sessions and pageviews with yearMonth dimension since 1 year ago 
$analyticsData = Analytics::performQuery(
    Period::years(1),
    'ga:sessions', <- metric!!! (YAYYYY!!) or 'ga:sessions, ga:pageviews' which doesnt go below
    [
        'metrics' => 'ga:sessions, ga:pageviews', <---- WTF is this????
        'dimensions' => 'ga:yearMonth'
    ]
);
