### ISSUE TITLE
[First Time Usage] Analytics Data returns null, is it normal?

### ISSUE THREAD

**Issue by pratamatama** [spatie/laravel-analytics#291]
I just created my first website & google account for Google Analytics API. I followed the steps provided but it seems like I don't get any value from it. Is it normal?

Here is some picture, take a look
![screenshot 6](https://user-images.githubusercontent.com/42239243/47614347-42e31b00-dad1-11e8-9ca6-ae5e0c744189.png)
![screenshot 7](https://user-images.githubusercontent.com/42239243/47614349-44144800-dad1-11e8-9c78-e24e03fcfaa1.png)

**Comment by xron89** [comment]
You said you just created a google analytics account. Do you have 7 days worth of data?

**Comment by pratamatama** [comment]
@xron89  no, I just created it today and I'm curious about it. There is no explanation on the docs about what will I get if the account is a brand new one. Could you explain, please? It might be useful for a newbs like me.

**Comment by xron89** [comment]
This package pulls data from Google analytics to display on your website. If you have an admin area and wish to display to the other users google analytic data you should use this package. 

So you need a google analytics account with some historical data in, else when you make the request its empty. It sounds like you haven't used google analytics much before so I recommend reading/watch some videos on how Google analytics work.

The reason you have no data is because you've asked to grab the last 7 days worth of google analytic data and you have 0 days as you just created the account.

**Comment by pratamatama** [comment]
Thanks @xron89 for the explanation, now I understand. Thank you very much.
