### ISSUE TITLE
How to use a dimension filter?

### ISSUE THREAD

**Issue by stijnwesterhof** [spatie/laravel-analytics#298]
I'm trying to add a dimension filter to my query.
`
$analyticsData = Analytics::performQuery(
            Period::years(1),
            'ga:adClicks,ga:CPC,ga:adCost,ga:transactions,ga:itemRevenue',
            [
                'dimensions' => 'ga:date'
            ],
            [
                'dimensionFilterClauses' => [
                    'filters' => [
                        'dimensionName' => 'ga:adwordsAdGroupID',
                        "operator" => "EXACT",
                        "expressions" => ["64882517676"]
                    ]
                ]
            ]
        );
`

I tried a lot of things, but I cant' figure out what I'm doing wrong.

**Comment by xiewxin** [comment]
Hey, do you know how to use the filter?

**Comment by sanderdewijs** [comment]
At first I also thought using the nested array for setting the filter properties was the way to go. While reading the Google's Core Reporting API Docs it says that all requests to the API are in fact URL encoded strings.

So instead of adding the parameters as nested arrays, you can just add the entire filter query as an url encoded string like so:

```
 'metrics'    => 'ga:pageviews',
 'dimensions' => 'ga:date,ga:dimension1',
 'filters'    => "ga:dimension1==stringtofilterby",
```
