### ISSUE TITLE
Use laravel-analytics 

### ISSUE THREAD

**Issue by developer-context** [spatie/laravel-analytics#344]
How could I use this same tool but to obtain the analytics of different accounts?

**Comment by AlexVanderbist** [comment]
Hi! You can simply ignore the values in the config file and use the `Analytics` class directly. Have a look at the service provider for an example of how to insatiate the `Analytics` class:

```php
 // These keys are the same as the config file
$analyticsConfig = [
    'view_id' => env('ANALYTICS_VIEW_ID'),
    'service_account_credentials_json' => storage_path('app/analytics/service-account-credentials.json'),
    'cache_lifetime_in_minutes' => 60 * 24,
    'cache' => [
        'store' => 'file',
    ],
];

$client AnalyticsClientFactory::createForConfig($analyticsConfig);

$analytics = new Analytics($client, $config['view_id']);

// Use $analytics to get analytics 🚀
```

**Comment by chaaawles** [comment]
hello @AlexVanderbist. I'm trying to implement what you've answered before. But I got stuck in an error saying `Call to undefined method Spatie\Analytics\AnalyticsFacade::fetchVisitorsAndPageViews()` It seems like I'm using the AnalyticsFacade instead of Analytics when I'm doing `$analytics->fetchVisitorsAndPageViews(Period::days(7));` after your code above. Am I doing this wrong?
