### ISSUE TITLE
Allow users to add their Google Analytics account

### ISSUE THREAD

**Issue by WebMedic-X** [spatie/laravel-analytics#354]
Hi Spatie,

Hope all is well and thank you for the superb Laravel support you have been giving the community!

Working on a dashboard where anyone can click a button and give us access to their Google Analytics view.

Would this be possible with your package? it seems that we need to manually add the service account email to each account?

Thank you

**Comment by joeelia** [comment]
No this is not possible with the package. You would want to use Google Oauth2 and allow the Analytics Read Only scope. 

Dealing with oauth2 takes quite a bit of leg work to around the refresh_token since it has so many conditions on when it expires and when it needs to be used to set an access_tolen.

**Comment by WebMedic-X** [comment]
Thanks for sharing @joeelia 

Looked into the oauth tokens and seems okay, we can request offline access and refresh the token as needed

Not sure if I am missing something?

The current method of having to add a service account isn’t friendly for web apps that on board users (ex SaaS) 

Why not add it in @freekmurze? 😄

**Comment by freekmurze** [comment]
I currently have no time to spend on this package. If you need this, send a PR. 👍
