### ISSUE TITLE
Why PHP 7?

### ISSUE THREAD

**Issue by juniorb2ss** [spatie/laravel-analytics#74]
ElasticBeanstalk deploy on AWS only has PHP 5.6.21 version or less. Why PHP is ^7?

:-1:

**Comment by freekmurze** [comment]
Hi,

I don't see why our package requirements should mirror what ElasticBeanstalk on AWS requires.

For our own internal projects we are not using PHP 5 anymore. That's why our packages do not support it any more. More info here: https://murze.be/2016/01/why-we-are-requiring-php-7-for-our-new-packages/

These are your options:
- use v1 of this package which has PHP 5 compatiblity
- fork this package and maintain your own PHP 5 version
- use another package
